#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Android.TagView.Resource", IsApplication=false)]

namespace Xamarin.Android.TagView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int lineMargin = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int tagMargin = 2130771969;
			
			// aapt resource value: 0x7f010005
			public static int textPaddingBottom = 2130771973;
			
			// aapt resource value: 0x7f010002
			public static int textPaddingLeft = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int textPaddingRight = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int textPaddingTop = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int tv_tag_item_contain = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int tv_tag_item_delete = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int tagview_item = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TagView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int TagView_lineMargin = 0;
			
			// aapt resource value: 1
			public static int TagView_tagMargin = 1;
			
			// aapt resource value: 5
			public static int TagView_textPaddingBottom = 5;
			
			// aapt resource value: 2
			public static int TagView_textPaddingLeft = 2;
			
			// aapt resource value: 3
			public static int TagView_textPaddingRight = 3;
			
			// aapt resource value: 4
			public static int TagView_textPaddingTop = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
